"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class imu_data(object):
    __slots__ = ["roll", "yaw", "pitch", "acc", "angle_speed"]

    __typenames__ = ["double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, None, [3], [3]]

    def __init__(self):
        self.roll = 0.0
        self.yaw = 0.0
        self.pitch = 0.0
        self.acc = [ 0.0 for dim0 in range(3) ]
        self.angle_speed = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(imu_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.roll, self.yaw, self.pitch))
        buf.write(struct.pack('>3d', *self.acc[:3]))
        buf.write(struct.pack('>3d', *self.angle_speed[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imu_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imu_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = imu_data()
        self.roll, self.yaw, self.pitch = struct.unpack(">ddd", buf.read(24))
        self.acc = struct.unpack('>3d', buf.read(24))
        self.angle_speed = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if imu_data in parents: return 0
        tmphash = (0x9dbe0e8b0dcaafb8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if imu_data._packed_fingerprint is None:
            imu_data._packed_fingerprint = struct.pack(">Q", imu_data._get_hash_recursive([]))
        return imu_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", imu_data._get_packed_fingerprint())[0]

